# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: '[DRAFT] Максим Сошнев'
title: '[DRAFT] Инженер по разработке ПО, middle'

email: soshnev.maxim11@gmail.com
phone: +7-(911)-724-67-08

# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# linkedin_username: jekyll

# Additional icon links
additional_links:
- title: Telegram
  icon: "fab fa-telegram"
  url: https://t.me/MSoshnev

# About Section
about_title: "О себе"
about_profile_image: images/me.jpg
about_content: |
  'Дорогой рекрутер, резюме IN PROGRESS'

content:
  - title: Технические навыки
    layout: list
    content:
      - layout: top-left
        description: |
          Дорогой рекрутер, резюме IN PROGRESS

  - title: Опыт работы
    layout: list
    content:
      - layout: top
        border: weak
        title: YADRO
        sub_title: Инженер по разработке ПО, middle
        caption: июнь 2022 - настоящее время
        link: https://yadro.com/
        quote: >
          Компания-разработчик ИТ-оборудования
        description: |

          Стек: <mark>Python</mark>, <mark>fastapi</mark>, <mark>aiohttp</mark>, <mark>Postgres</mark>, <mark>MongoDB</mark>, <mark>SQLAlchemy</mark>, <mark>alembic</mark>, <mark>docker</mark>, <mark>Jenkins</mark>

          Обязанности:

            - Разработка backend-приложений, инструментов тестировния и отладки системы хранения данных Tatlin Unified;

            - Разработка и улучшение инструментов DevOps для продуктовых команд;

            - Разработка инструментария для оркестрации пайплайна сборки продукта.

      - layout: top
        border: weak
        title: Yandex practicum
        sub_title: Код ревьювер
        caption: май 2023 - настоящее время
        link: http://emzior.ru/
        quote: >
          Платформа онлайн-образования
        description: |
          Обязанности:
            - Проводить code review работ студентов.

      - layout: top
        border: weak
        title: Emzior Technologies
        sub_title: Инженер-программист, middle
        caption: апрель 2022 - июнь 2023
        link: http://emzior.ru/
        quote: >
          Компания-разработчик программного обеспечения для телекоммуникационного оборудования
        description: |
          Стек: <mark>Python</mark>, <mark>pytest</mark>, <mark>C</mark>, <mark>clish</mark>, <mark>bash</mark>, <mark>Jenkins</mark>

          Обязанности:

          - Разработка нового функционала и поддержка существующей кодовой базы для системы управления программным маршрутизатором.

          - Разработка text-based пользовательских интерфейсов.

          - Доработка и поддержка реализаций сетевых протоколов.

          - Настройка разрабатываемого ПО на процессорных платах и виртуальных машинах. Настройка сетевых топологий.

          - Разработка тестовых сценариев и тестирование маршрутизаторов.

      - layout: top
        border: weak
        title: Wargaming (World Of Warships)
        sub_title: Программист, стажёр
        caption: май 2021 — август 2021
        link: https://www.worldofwarships.ru/
        quote: >
          Компания-разработчик компьютерных игр
        description: |
          Программист в проекте "Корабли".

          Стек: <mark></mark>, <mark>Python</mark>

          Обязанности:

          - Разработка игрового инструментария средствами <mark>C++</mark> и <mark>Python</mark>.

          - Оптимизация существующего механизма балансировки нагрузки на сервера.

      - layout: top
        border: weak
        title: ФГУП "НПП Гамма"
        sub_title: Техник ТЗИ
        caption: июль 2020 — май 2021
        link: https://nppgamma.ru
        quote: >
          Компания-интегратор технических и программно-аппаратных средств защиты информации.
        description: |
          Техник в отделе сертификационных испытаний программно-аппаратных средств.

          Стек: <mark>Python</mark>, <mark>C++</mark>, <mark>MySQL</mark>

          Обязанности:

          - Проведение сертификационных испытаний программного продукта, направленных на поиск недекларированных возможностей согласно документам ФСТЭК России.

          - Разработка инструментария для проведения сертификационных испытаний (средствами языков <mark>C++</mark>, <mark>Python</mark>).

          - Участие в опытно-конструкторских работах. Разработка инструментария фаззинг-тестирования программных систем (средствами языка <mark>C++</mark>).

  - title: Образование
    layout: list
    content:
      - layout: top
        border: weak
        title: Санкт-Петербургский политехнический университет Петра Великого (СПБПУ)
        sub_title: Специалист по кибербезопасности и защиты информации
        caption: сентябрь 2018 - июнь 2023
        # quote: >
          # Short institution or course description (optional)
        description: |
          Институт: Институт Кибербезопасности и Защиты Информации (ИКиЗИ)

          Направление подготовки: Информационная Безопасность Автоматизированных Систем (10.05.03)

          Квалификация: специалист

          ВКР: Метод защиты от угроз извлечения модели машинного обучения (https://elib.spbstu.ru/dl/3/2023/vr/vr23-1876.pdf/en/info)

  - title: Дополнительное образование
    layout: list
    content:
      - layout: top
        border: weak
        title: Cisco Network Academy
        caption: сентябрь 2020 - апрель 2021
        description: |
          Пройдены курсы:

            - Routing and switching

            - Network Security

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
